
@startuml vuln-status
hide empty description


state Inbox {
    state New
    state Reopened
}
[*] -d-> Inbox : Scan

state Analyzed {
    state Unresolved
    state Mitigated
    state Accepted
    state FalsePositive
}

Inbox -d-> Analyzed : Human

Analyzed -u-> New : Human
Analyzed -d-> Gone : Scan
Gone -u-> Reopened : Scan


@enduml